### ISSUE TITLE
Move to @reasonml-community or @reasonml-labs?

### ISSUE THREAD

**Issue by fakenickels** [reasonml-community/reason-apollo-hooks#123]
Given the lib importance to the community it makes sense to have it under the community control.

**Comment by peterpme** [comment]
Hey @fakenickels, this is a great idea! reasonml-community would be great :smile:

**Comment by fakenickels** [comment]
It's done! We'll be keeping the same npm package name

**Comment by peterpme** [comment]
Thank you :smile:

I wonder if we can do the same with reason-apollo

**Comment by fakenickels** [comment]
Probably we can try to reach the Apollo team!
